version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      APP_ID: $APP_ID
      APP_CODE: $APP_CODE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASS: $POSTGRES_PASS
      POSTGRES_DBNAME: $POSTGRES_DBNAME
  db:
    image: kartoza/postgis:11.0-2.5
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/setup-db.sql
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASS: $POSTGRES_PASS
      POSTGRES_DBNAME: $POSTGRES_DBNAME
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - db
